<a href="https://colab.research.google.com/github/KevinSolano22/Carpeta3/blob/main/Transmision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Definir la matriz
A = np.array([[2267.09, -211.07],
              [-211.07, 2267.09]])

# Calcular la matriz inversa
try:
    inversa = np.linalg.inv(A)
    print("La matriz inversa es:")
    print(inversa)
except np.linalg.LinAlgError:
    print("La matriz no tiene inversa (es singular).")


La matriz inversa es:
[[4.44950894e-04 4.14256978e-05]
 [4.14256978e-05 4.44950894e-04]]


In [ ]:
import numpy as np

# Definir una matriz 3x2
A = np.array([[-498.92, -188.99],
              [-108.64, -204.91],
              [-101.29, -71.45]])

# Definir una matriz 2x2
B = np.array([[4.44950894e-04, 4.14256978e-05],
              [4.14256978e-05, 4.44950894e-04]])

# Multiplicar las matrices
C = A @ B  # También puedes usar np.dot(A, B)

print("El resultado de la multiplicación es:")
print(C)


El resultado de la multiplicación es:
[[-0.22982394 -0.10475938]
 [-0.056828   -0.09567538]
 [-0.04802894 -0.03598775]]


In [ ]:
import numpy as np

# Definir una matriz 3x2
A = np.array([[-0.22982394, -0.10475938],
              [-0.056828,   -0.09567538],
              [-0.04802894, -0.03598775]])

# Definir una matriz 2x3
B = np.array([[-498.92, -108.64, -101.29],
              [-188.99, -204.91, -71.45]])

# Multiplicar las matrices
C = A @ B  # También puedes usar np.dot(A, B)

print("El resultado de la multiplicación es:")
print(C)


El resultado de la multiplicación es:
[[134.46223537  46.4343174   30.76392458]
 [ 46.43431583  25.77863604  12.59211402]
 [ 30.76392362  12.59211389   7.43617607]]


In [ ]:
import numpy as np

# Definir la primera matriz 3x3
A = np.array([[2585.83, -145.78, -165.36],
              [-145.78, 2557.32, -144.52],
              [-165.36, -144.52, 2543.51]])

# Definir la segunda matriz 3x3
B = np.array([[134.462, 46.434, 30.764],
              [46.434, 25.778, 12.592],
              [30.764, 12.592, 7.436]])

# Restar las matrices
C = A - B

print("El resultado de la resta es:")
print(C)


El resultado de la resta es:
[[2451.368 -192.214 -196.124]
 [-192.214 2531.542 -157.112]
 [-196.124 -157.112 2536.074]]


In [ ]:
import numpy as np

# Definir la matriz de impedancias Zabc extraída de la imagen
Zabc = np.array([
    [0.261 + 0.8849j, 0.0592 + 0.2874j, 0.0592 + 0.2927j, 0.0592 + 0.273j, 0.0592 + 0.3415j, 0.0592 + 0.3074j],
    [0.261 + 0.8849j, 0.0592 + 0.2865j, 0.0592 + 0.3415j, 0.0592 + 0.3415j, 0.0592 + 0.2865j, 0.0592 + 0.3423j],
    [0.261 + 0.8849j, 0.0592 + 0.3064j, 0.261 + 0.8849j, 0.0592 + 0.3415j, 0.0592 + 0.3423j, 0.0592 + 0.2727j],
    [0.261 + 0.8744j, 0.0592 + 0.2865j, 0.0592 + 0.3415j, 0.261 + 0.8849j, 0.0592 + 0.2874j, 0.0592 + 0.273j],
    [0.261 + 0.8849j, 0.0592 + 0.2874j, 0.0592 + 0.3423j, 0.0592 + 0.3074j, 0.261 + 0.8849j, 0.0592 + 0.3415j],
    [0.261 + 0.8849j, 0.0592 + 0.2874j, 0.0592 + 0.2727j, 0.0592 + 0.273j, 0.0592 + 0.3415j, 0.261 + 0.8849j]
])

# Definir la matriz de transformación S
a = np.exp(1j * 2 * np.pi / 3)  # a = e^(j120°)
a2 = a**2  # a^2 = e^(j240°)

S = np.array([
    [1, 1, 1],
    [1, a2, a],
    [1, a, a2]
], dtype=complex)

S_inv = (1/3) * np.array([
    [1, 1, 1],
    [1, a, a2],
    [1, a2, a]
], dtype=complex)

# Construir la matriz de transformación 6x6 para doble circuito
S_block = np.block([
    [S_inv, np.zeros((3,3))],
    [np.zeros((3,3)), S_inv]
])

# Transformación para obtener la matriz de impedancias en secuencia
Z012 = S_block @ Zabc @ np.block([
    [S, np.zeros((3,3))],
    [np.zeros((3,3)), S]
])

# Extraer valores Z0, Z1, Z2
Z0 = np.mean(np.diag(Z012[:3, :3]))  # Secuencia 0
Z1 = np.mean(np.diag(Z012[3:, 3:]))  # Secuencia 1
Z2 = np.mean(np.diag(Z012[3:, 3:]))  # Secuencia 2 (igual a Z1 en balanceado)

# Imprimir resultados
print("Matriz Z012:")
print(np.round(Z012, 4))
print("\nImpedancia de secuencia:")
print(f"Z0 = {Z0:.4f}")
print(f"Z1 = {Z1:.4f}")
print(f"Z2 = {Z2:.4f}")
